- name: Kalliope Yandex Maps + Uber neuron
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install uber lib dependencies"
      pip:
        name: uber_rides
