- name: Kalliope Google Maps neuron
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install uber lib dependencies"
      pip:
        name: uber-rides
        version: 0.4.1
    - name: "Install gmaps lib dependencies"
      pip:
        name: googlemaps
        version: 2.4.5
